apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: audit-zone
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: nginx
      command:
        - sleep
        - "86400"
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 32Mi
